services:
  - type: web
    name: chatterbox-tts-api
    env: python
    plan: starter
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1" 