services:
  - type: web
    name: chatterbox-tts-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTORCH_ENABLE_MPS_FALLBACK
        value: "1"
      - key: PORT
        value: "8000"
    disk:
      name: chatterbox-models
      sizeGB: 10
      mountPath: /opt/render/project/models 